### PR TITLE
Handle missing attributes - Fixes #3

### LINKED ISSUE #3: Implement missing attribute handling

### PR DESCRIPTION
**Pull request by za419**
@alanwoj16 said in #3 that this should work.

### CODE REVIEW

**Comment by alanwoj16** [comment]
I made it a be able to take in an attribute name or class so I can take advantage of finding the mode for any attribute in missing_attributes

**Comment by za419** [comment]
Yeah, I like the change. It's just that I think I remember the spec saying we can't change the signatures in ID3, which I interpret to mean that they expect functions with the original signatures to exist... Hence my suggestion for the defaulting of `a_name`.

**Comment by alanwoj16** [comment]
Hmm I'm not sure what they mean by signatures but I thought that I just can't change the way the four functions provided were defined

**Comment by za419** [comment]
Oh, is modes not one of the ones they provided?

Yeah, in that case we should be good

**Comment by alanwoj16** [comment]
No, they only provided ID3, prune, test, and evaluate. All of the other functions are ones that I put in

**Comment by za419** [comment]
I'll fix this merge conflict. One sec..

**Comment by za419** [comment]
Okay, great. Forget I said anything about it!

**Pull request merged**
